networks:
  pgnet:
    driver: bridge

services:

  pgmaster:
    image: postgres:16
    container_name: pgmaster
    restart: unless-stopped
    networks:
      - pgnet
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - ./volumes/pgmaster:/var/lib/postgresql/data

  pgslave:
    image: postgres:16
    container_name: pgslave
    restart: unless-stopped
    networks:
      - pgnet
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - ./volumes/pgslave:/var/lib/postgresql/data

  pgasyncslave:
    image: postgres:16
    container_name: pgasyncslave
    restart: unless-stopped
    networks:
      - pgnet
    ports:
      - "25432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - ./volumes/pgasyncslave:/var/lib/postgresql/data

  haproxy:
    image: haproxy:latest
    ports:
      - "5433:5432"
      - "8404:8404"
    networks:
      - pgnet
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - pgasyncslave
      - pgslave

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    networks:
      - pgnet
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    networks:
      - pgnet
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_running" ]
      interval: 10s
      timeout: 5s
      retries: 5

  dialog-service:
    image: ghcr.io/solo157/dialog-service:latest
    container_name: dialog-service
    restart: unless-stopped
    networks:
      - pgnet
    ports:
      - "9090:9090"
    depends_on:
      - redis
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - pgnet
    depends_on:
      - socialnetwork1
      - socialnetwork2

  socialnetwork1:
    image: ghcr.io/solo157/socialnetwork:latest
    container_name: socialnetwork1
    restart: unless-stopped
    networks:
      - pgnet
    depends_on:
      - pgmaster
      - rabbitmq
      - redis
      - haproxy
      - dialog-service
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

  socialnetwork2:
    image: ghcr.io/solo157/socialnetwork:latest
    container_name: socialnetwork2
    restart: unless-stopped
    networks:
      - pgnet
    depends_on:
      - pgmaster
      - rabbitmq
      - redis
      - haproxy
      - dialog-service
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
