spring:
  application:
    name: counter-service
  datasource:
    driver-class-name: org.postgresql.Driver
    master:
      url: ${SPRING_DATASOURCE_MASTER_URL:jdbc:postgresql://pgmaster:5432/postgres}
      username: ${SPRING_DATASOURCE_MASTER_USERNAME:postgres}
      password: ${SPRING_DATASOURCE_MASTER_PASSWORD:pass}
    readhaproxy:
      url: ${SPRING_DATASOURCE_READ_URL:jdbc:postgresql://haproxy:5432/postgres}
      username: ${SPRING_DATASOURCE_READ_USERNAME:postgres}
      password: ${SPRING_DATASOURCE_READ_PASSWORD:pass}
 #  datasource:
 #    url: jdbc:postgresql://${SPRING_DB_HOST:pgmaster}:${SPRING_DB_PORT:5432}/${SPRING_DB_NAME:socialnetwork}
 #    username: ${SPRING_DB_USER:postgres}
 #    password: ${SPRING_DB_PASSWORD:pass}
  sql:
    init:
      mode: always
      encoding: UTF-8
      schema-locations: classpath:db/counter_service_schema.sql
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_HOSTS:localhost:9092}
    consumer:
      group-id: counter-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    listener:
      # ACK только вручную, после успешного commit транзакции
      ack-mode: manual_immediate

server:
  port: 8092
