spring:
  application:
    name: socialnetwork

  datasource:
    driver-class-name: org.postgresql.Driver
    master:
      url: jdbc:postgresql://pgmaster:5432/postgres
      username: postgres
      password: pass
    slave1:
      url: jdbc:postgresql://pgslave:5432/postgres
      username: postgres
      password: pass
    slave2:
      url: jdbc:postgresql://pgasyncslave:5432/postgres
      username: postgres
      password: pass

  sql:
    init:
      mode: always