events {}

http {

    upstream socialnetwork {
        server socialnetwork1:8080;
        server socialnetwork2:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://socialnetwork;
        }
    }
}
