---
- name: Install docker
  apt:
    name:
      - docker.io
      - docker-compose-v2
    state: present
    update_cache: yes

- name: Enable Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes