- name: Stop and disable Zabbix Agent 2
  ansible.builtin.systemd:
    name: zabbix-agent2
    state: stopped
    enabled: false
  failed_when: false

- name: Remove Zabbix Agent 2
  ansible.builtin.apt:
    name: zabbix-agent2
    state: absent
    purge: true
    autoremove: true

- name: Remove Zabbix configuration
  ansible.builtin.file:
    path: /etc/zabbix
    state: absent

- name: Deploy with docker compose
  shell: |
    docker compose down
  args:
    chdir: /opt/app

- name: Deploy with docker compose for zabbix
  shell: |
    docker compose down
  args:
    chdir: /opt/app/zabbix